// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsQWV8GrmCBs3p4LyVWCY2TQpKSGV0kU8',
    appId: '1:777940063712:web:6189f60d95d6be4b5e8785',
    messagingSenderId: '777940063712',
    projectId: 'rent2go-fe7ed',
    authDomain: 'rent2go-fe7ed.firebaseapp.com',
    storageBucket: 'rent2go-fe7ed.firebasestorage.app',
    measurementId: 'G-1QDC2YBHK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3UbKr8VlMdeoYS-kSO3-hPlr46G-IXgs',
    appId: '1:777940063712:android:05b48f15015e7ad15e8785',
    messagingSenderId: '777940063712',
    projectId: 'rent2go-fe7ed',
    storageBucket: 'rent2go-fe7ed.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH8aw4PRnF9R-5pp7stonElbSoT6YZRCQ',
    appId: '1:777940063712:ios:456124695845f2e25e8785',
    messagingSenderId: '777940063712',
    projectId: 'rent2go-fe7ed',
    storageBucket: 'rent2go-fe7ed.firebasestorage.app',
    iosBundleId: 'com.upc.rent2go',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH8aw4PRnF9R-5pp7stonElbSoT6YZRCQ',
    appId: '1:777940063712:ios:456124695845f2e25e8785',
    messagingSenderId: '777940063712',
    projectId: 'rent2go-fe7ed',
    storageBucket: 'rent2go-fe7ed.firebasestorage.app',
    iosBundleId: 'com.upc.rent2go',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsQWV8GrmCBs3p4LyVWCY2TQpKSGV0kU8',
    appId: '1:777940063712:web:473baa33acf6ad135e8785',
    messagingSenderId: '777940063712',
    projectId: 'rent2go-fe7ed',
    authDomain: 'rent2go-fe7ed.firebaseapp.com',
    storageBucket: 'rent2go-fe7ed.firebasestorage.app',
    measurementId: 'G-R79KD4DGXV',
  );
}
